services:
  app:
    build: .
    ports:
      - "80:80"
    depends_on:
      - ollama
    networks:
      - ai-network

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_ORIGINS=*
    volumes:
      - ollama_data:/root/.ollama
    # deploy:
    #   resources:
    #     limits:
    #       memory: 1.5G
    networks:
      - ai-network

volumes:
  ollama_data:

networks:
  ai-network:
    driver: bridge